app/app/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views



urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace='main')),
    path('', include('pwa.urls')),
    path('',include('django.contrib.auth.urls')),
]

app/main/urls.py
from django.urls import path,include
from main import views

app_name='main'

urlpatterns = [
    path('', views.title_view, name='home'),
    path('add/', views.add_content, name='add'),
    path('<int:pk>', views.info_view, name='info'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/', views.Edit_Info, name='edit_info'),
    path('<int:pk>/edit/xaraktiristika', views.Edit_Xaraktiristika.as_view(), name='edit_xaraktiristika'),
    path('<int:pk>/edit/sxoleio', views.Edit_Sxoleio.as_view(), name='edit_sxoleio'),
    path('<int:pk>/edit/ekpedeftikoi', views.Edit_Ekpedeftikoi.as_view(), name='edit_ekpedeftikoi'),
    path('<int:pk>/edit/goneis', views.Edit_Goneis.as_view(), name='edit_goneis'),
    path('<int:pk>/edit/sindesmoi', views.Edit_Sindesmoi.as_view(), name='edit_sindesmoi'),
    
]

app/main/models.py
from django.db import models

# Create your models here.

class Asthenia(models.Model):
    onoma=models.CharField(max_length=100)
    orismos=models.TextField()
    
    def __str__(self):
        return f"{self.onoma}"
    
class Xaraktiristika(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    xaraktiristiko=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-Xaraktiristiko_{self.id}"

class Sxoleio(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    odigia=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-odigia_{self.id}"
    
class Ekpedeftikoi(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    odigia=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-odigia_{self.id}"
    
class Goneis(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    odigia=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-odigia_{self.id}"
    
class Perisotera(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    link=models.URLField()
    
    def __str__(self):
        return f"{self.asthenia}-link_{self.id}"

app/main/forms.py
from django import forms
from django.forms.models import inlineformset_factory
# from django.forms.models
from . import models

class AstheniaForm(forms.ModelForm):
    class Meta:
        model = models.Asthenia
        fields = [
            'onoma',
            'orismos',
        ]

AstheniaXaraktitistikaFormset = inlineformset_factory(models.Asthenia ,models.Xaraktiristika, fields=('xaraktiristiko',))
AstheniaSxoleioFormset = inlineformset_factory(models.Asthenia ,models.Sxoleio, fields=('odigia',))
AstheniaEkpedeftikoiFormset = inlineformset_factory(models.Asthenia ,models.Ekpedeftikoi, fields=('odigia',))
AstheniaGoneisFormset = inlineformset_factory(models.Asthenia ,models.Goneis, fields=('odigia',))
AstheniaPerisoteraFormset = inlineformset_factory(models.Asthenia ,models.Perisotera, fields=('link',))

app/main/views.py
from django.http.response import HttpResponseRedirect
from .models import *
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import FormView
from django.urls import reverse
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from . import forms 


def title_view(request):
    astheniesList = Asthenia.objects.all().order_by('onoma')
    context = {
        'astheniesList': astheniesList
    }
    return render(request, "main/titles.html", context)


def info_view(request, pk):
    asthenia = get_object_or_404(Asthenia, id=pk)
    xaraktiristika=Xaraktiristika.objects.filter(asthenia=asthenia.id)
    sxolio=Sxoleio.objects.filter(asthenia=asthenia.id)
    ekpedeftikoi=Ekpedeftikoi.objects.filter(asthenia=asthenia.id)
    goneis=Goneis.objects.filter(asthenia=asthenia.id)
    perisotera=Perisotera.objects.filter(asthenia=asthenia.id)
    
    
    context={
        'asthenia':asthenia,
        'xaraktiristika':xaraktiristika,
        'sxolio':sxolio,
        'ekpedeftikoi':ekpedeftikoi,
        'goneis':goneis,
        'perisotera':perisotera,
    }
    return render(request, "main/info.html", context)

@login_required
def add_content(request):
    if request.method == 'POST':
        form = forms.AstheniaForm(request.POST)
        if form.is_valid():
            form.save()
            onoma = form.cleaned_data['onoma']
            asthenia = get_object_or_404(Asthenia, onoma=onoma)
            return redirect("/"+str(asthenia.id))
    return render(request, "main/add.html", {})


@login_required
def Edit_Info(request, pk):
        obj= get_object_or_404(Asthenia, id=pk)
        
        form = forms.AstheniaForm(request.POST or None, instance= obj)
        context= {'form': form}

        if form.is_valid():
            obj= form.save(commit= False)
            obj.save()
            messages.success(request, "Αποθηκεύτηκε")
            context= {
                    'form': form,
                    }
        return render(request, 'main/edit/edit_info.html', context)

@login_required
def delete(request, pk):
    obj= get_object_or_404(Asthenia, id=pk)
    if request.method=="POST":
        obj.delete()
        return redirect('/')
    context={
        'item':obj,
    }
    return render(request,'main/delete.html',context)

class Edit_Xaraktiristika(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_xaraktiristika.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaXaraktitistikaFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_xaraktiristika', kwargs={'pk':self.object.pk})
    
class Edit_Sxoleio(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_sxoleio.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaSxoleioFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_sxoleio', kwargs={'pk':self.object.pk})
    
class Edit_Ekpedeftikoi(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_ekpedeftikoi.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaEkpedeftikoiFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_ekpedeftikoi', kwargs={'pk':self.object.pk})
    
class Edit_Goneis(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_goneis.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaGoneisFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_goneis', kwargs={'pk':self.object.pk})
    
class Edit_Sindesmoi(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_sindesmoi.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaPerisoteraFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_sindesmoi', kwargs={'pk':self.object.pk})

app/main/templates/main/add.html
{% extends 'base.html' %}
{% load group %}

{% block css %}
<style>
    /* label focus color */
    .input-field input[type=text]:focus + label, .materialize-textarea:focus:not([readonly]) + label {
        color: #01579b !important;
        }

    /* label underline focus color */
        .input-field input[type=text]:focus, .materialize-textarea:focus:not([readonly]) {
        border-bottom: 1px solid #01579b !important;
        box-shadow: 0 1px 0 0 #01579b !important;
        }
    #container,
    html,
    body {
        height: 90%;
    }

</style>
{% endblock %}

{% block content %}

{% include 'nav.html' %}
{% if request.user|has_group:"admin" %}
<div id="container" class="container ">
    <form method="POST" action="." >
        {% csrf_token %}
        <div class="input-field">
            <input type="text" id="onoma" class="validate" name="onoma" required>
            <label for="onoma">Όνομα Ασθένειας</label>
        </div>
        <div class="input-field">
            <textarea type="text" id="orismos" class="materialize-textarea" name="orismos" required></textarea>
            <label for="orismos">Ορισμός Ασθένειας</label>
        </div>
        
            <button class="btn waves-effect waves-light light-blue darken-4 right" type="submit" name="action">Προσθεστε
                <i class="material-icons right">send</i>
            </button>
        
    </form>
</div>
{% endif %}
{% endblock %}
    {% block javascript %}
    {% if True != request.user|has_group:"admin" %}
        <script>
            window.location.replace("../");
        </script>
    {% endif %}
    {% endblock %}

app/main/templates/main/delete.html
{% extends 'base.html' %}

{% block content %}

{% include 'nav.html' %}
<form method="post" action=".">
    {% csrf_token %}
    <h5>Θέλετε να διαγράψετε το <b class="light-blue-text text-darken-4">{{item}}</b>?</h5>
    <button type="submit" class="btn red">ΔΙΑΓΡΑΦΗ</button>
    <a href="{% url 'main:edit_info' pk=item.id%}">ΑΚΥΡΩΣΗ</a>
</form>
    
{% endblock %}

app/main/templates/main/info.html
{% extends 'base.html' %}
{% load group %}

{% block css %}
<style>
    html,
    body {
        height: 100%;
    }
    .block {
        min-height: 100%;
    }
    ol {
        width: 90%;
    }

    .pin-top {
        position: relative;
    }

    .pin-bottom {
        position: relative;
    }

    .pinned {
        position: fixed !important;
    }
    h6{
        text-transform: uppercase;
    }
    h2{
        margin: 20px;
    }
    #edit{
        margin-top:13px;
    }
</style>
{% endblock %}


{% block content %}

<h2 class="center-align  light-blue-text text-darken-4">{{asthenia.onoma}}</h2>

<div id="xaraktiristika" class="block">
    <nav class="pushpin-nav" data-target="xaraktiristika">
        <div class="nav-wrapper light-blue darken-4light-blue darken-4">
            <div class="container">
                <a href="" class="brand-logo">Χαρακτηριστικά</a>
                <a id="edit" class="hide btn-small btn-floating waves-effect grey lighten-3 right" href="{% url 'main:edit_xaraktiristika' pk=asthenia.id %}">
                    <i id="edit_icon" class="material-icons light-blue-text text-darken-4 ">edit</i></a>
            </div>
        </div>
    </nav>
    <ol>
        <br>
        {% for item in xaraktiristika %}
        <br>
        <li>
            {{item.xaraktiristiko}}
        </li>
        {% endfor %}
        <br>
        <br>
    </ol>
</div>

<div id="sxoleio" class="block">
    <nav class="pushpin-nav" data-target="sxoleio">
        <div class="nav-wrapper light-blue darken-4">
            <div class="container">
                <a href="" class="brand-logo">Σχολείο</a>
                <a id="edit" class="hide btn-small btn-floating waves-effect grey lighten-3 right" href="{% url 'main:edit_sxoleio' pk=asthenia.id %}">
                    <i id="edit_icon" class="material-icons light-blue-text text-darken-4 ">edit</i></a>
            </div>
        </div>
    </nav>
    <ol>
        <br>
        {% for item in sxolio %}
        <br>
        <li>
            {{item.odigia}}
        </li>
        {% endfor %}
        <br>
        <br>
    </ol>
</div>

<div id="ekpedeftikoi" class="block">
    <nav class="pushpin-nav" data-target="ekpedeftikoi">
        <div class="nav-wrapper light-blue darken-4">
            <div class="container">
                <a href="" class="brand-logo">Εκπεδευτικοί</a>
                <a id="edit" class="hide btn-small btn-floating waves-effect grey lighten-3 right" href="{% url 'main:edit_ekpedeftikoi' pk=asthenia.id %}">
                    <i id="edit_icon" class="material-icons light-blue-text text-darken-4 ">edit</i></a>
            </div>
        </div>
    </nav>
    <ol>
        <br>
        {% for item in ekpedeftikoi %}
        <br>
        <li>
            {{item.odigia}}
        </li>
        {% endfor %}
        <br>
        <br>
    </ol>
</div>

<div id="goneis" class="block">
    <nav class="pushpin-nav" data-target="goneis">
        <div class="nav-wrapper light-blue darken-4">
            <div class="container">
                <a href="" class="brand-logo">Γονείς</a>
                <a id="edit" class="hide btn-small btn-floating waves-effect grey lighten-3 right" href="{% url 'main:edit_goneis' pk=asthenia.id %}">
                    <i id="edit_icon" class="material-icons light-blue-text text-darken-4 ">edit</i></a>
            </div>
        </div>
    </nav>
    <ol>
        <br>
        {% for item in goneis %}
        <br>
        <li>
            {{item.odigia}}
        </li>
        {% endfor %}
        <br>
        <br>
    </ol>
</div>



<footer class="page-footer light-blue darken-4">
    <div class="container ">
        <div class="row">
        <div class="col l6 s12">
            <a id="edit" class="hide btn-small btn-floating waves-effect grey lighten-3 right" href="{% url 'main:edit_sindesmoi' pk=asthenia.id %}">
                <i id="edit_icon" class="material-icons light-blue-text text-darken-4 ">edit</i></a>
            <h6 class="white-text" ><b>Περισσοτερες Πληροφοριες</b> </h6>
            <p class="grey-text text-lighten-4">Για περισσότερες πληροφορίες συμβουλευτείτε τους παρακάτω συνδέσμους
        </p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Σύνδεσμοι</h5>
                <ul>
                    {% for item in perisotera %}
                    <li><a class="grey-text text-lighten-3" href="{{item.link}}" target="_blank">
                        {{item.link}}
                    </a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2021 Frederick University
            <a class="grey-text text-lighten-4 right" href="../" ><i class="tiny material-icons">home</i> Αρχική</a>
        </div>
    </div>
</footer>
{% endblock %}

{% block javascript %}
{% if request.user|has_group:"admin" %}
    <script>
    document.querySelectorAll('[id=edit]').forEach(element=>{ 
    element.classList.remove("hide");
    });
    </script>
    {% endif %}
<script>
    $(document).ready(function () {
        $('.pushpin').pushpin();
    });

    $('.pushpin-nav').each(function () {
        var $this = $(this);
        var $target = $('#' + $(this).attr('data-target'));
        $this.pushpin({
            top: $target.offset().top,
            bottom: $target.offset().top + $target.outerHeight() - $this.height()
        });
    });
</script>
{% endblock %}

app/main/templates/main/titles.html
{% extends 'base.html' %}
{% load group %}

{% block css %}
<style>
    .collapsible{
        margin: 0px;
    }
    #edit_icon{
        margin-right: 0px;
        font-size: 15px;
    }
    #edit{
        margin-top: 10px;
        margin-left: auto;
    }

    #add{
        position: fixed;
        bottom: 10px;
        right: 45%;
    }

    @media (min-width : 1025px) {
        .collapsible{
            width: 70%;
            margin:auto;
        }
    }
</style>


{% endblock %}

{% block content %}

{% include 'nav.html' %}

<ul class="collapsible" data-collapsible="accordion" >


    {% for asthenia in astheniesList%}
    <li>
        <div class="collapsible-header">
            <h5>{{ asthenia.onoma }}</h5>
            <a id="edit" class="hide btn-small btn-floating waves-effect light-blue darken-4 right" href="{% url 'main:edit_info' pk=asthenia.id %}"><i id="edit_icon" class="material-icons ">edit</i></a>
        </div>
        <div class="collapsible-body">
            <p>{{ asthenia.orismos }}</p>
            <a class="right waves-effect waves-light btn light-blue darken-4" href="{{ asthenia.id }}"><i
                    class="material-icons right">arrow_forward</i>Μαθε Περισοτερα</a>
            <h1></h1>
        </div>
    </li>
    
    {% endfor %}
</ul>
<a id="add" class="hide btn-floating btn waves-effect waves-light light-blue darken-4" href="./add"><i class="material-icons">add</i></a>
{% endblock %}

{% block javascript %}
{% if request.user|has_group:"admin" %}
    <script>
    document.querySelectorAll('[id=edit]').forEach(element=>{ 
    element.classList.remove("hide");
    });
    document.getElementById('add').classList.remove("hide");
    </script>
    {% endif %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
{% endblock %}