app/app/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views



urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace='main')),
    path('', include('pwa.urls')),
    path('',include('django.contrib.auth.urls')),
]

app/main/urls.py
from django.urls import path,include
from main import views

app_name='main'

urlpatterns = [
    path('', views.title_view, name='home'),
    path('add/', views.add_content, name='add'),
    path('<int:pk>', views.info_view, name='info'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/', views.Edit_Info, name='edit_info'),
    path('<int:pk>/edit/xaraktiristika', views.Edit_Xaraktiristika.as_view(), name='edit_xaraktiristika'),
    path('<int:pk>/edit/sxoleio', views.Edit_Sxoleio.as_view(), name='edit_sxoleio'),
    path('<int:pk>/edit/ekpedeftikoi', views.Edit_Ekpedeftikoi.as_view(), name='edit_ekpedeftikoi'),
    path('<int:pk>/edit/goneis', views.Edit_Goneis.as_view(), name='edit_goneis'),
    path('<int:pk>/edit/sindesmoi', views.Edit_Sindesmoi.as_view(), name='edit_sindesmoi'),
    
]

app/main/models.py
from django.db import models

# Create your models here.

class Asthenia(models.Model):
    onoma=models.CharField(max_length=100)
    orismos=models.TextField()
    
    def __str__(self):
        return f"{self.onoma}"
    
class Xaraktiristika(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    xaraktiristiko=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-Xaraktiristiko_{self.id}"

class Sxoleio(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    odigia=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-odigia_{self.id}"
    
class Ekpedeftikoi(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    odigia=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-odigia_{self.id}"
    
class Goneis(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    odigia=models.TextField()
    
    def __str__(self):
        return f"{self.asthenia}-odigia_{self.id}"
    
class Perisotera(models.Model):
    asthenia=models.ForeignKey(Asthenia,on_delete=models.CASCADE)
    link=models.URLField()
    
    def __str__(self):
        return f"{self.asthenia}-link_{self.id}"

app/main/forms.py
from django import forms
from django.forms.models import inlineformset_factory
# from django.forms.models
from . import models

class AstheniaForm(forms.ModelForm):
    class Meta:
        model = models.Asthenia
        fields = [
            'onoma',
            'orismos',
        ]

AstheniaXaraktitistikaFormset = inlineformset_factory(models.Asthenia ,models.Xaraktiristika, fields=('xaraktiristiko',))
AstheniaSxoleioFormset = inlineformset_factory(models.Asthenia ,models.Sxoleio, fields=('odigia',))
AstheniaEkpedeftikoiFormset = inlineformset_factory(models.Asthenia ,models.Ekpedeftikoi, fields=('odigia',))
AstheniaGoneisFormset = inlineformset_factory(models.Asthenia ,models.Goneis, fields=('odigia',))
AstheniaPerisoteraFormset = inlineformset_factory(models.Asthenia ,models.Perisotera, fields=('link',))

app/main/views.py
from django.http.response import HttpResponseRedirect
from .models import *
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import FormView
from django.urls import reverse
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from . import forms 


def title_view(request):
    astheniesList = Asthenia.objects.all().order_by('onoma')
    context = {
        'astheniesList': astheniesList
    }
    return render(request, "main/titles.html", context)


def info_view(request, pk):
    asthenia = get_object_or_404(Asthenia, id=pk)
    xaraktiristika=Xaraktiristika.objects.filter(asthenia=asthenia.id)
    sxolio=Sxoleio.objects.filter(asthenia=asthenia.id)
    ekpedeftikoi=Ekpedeftikoi.objects.filter(asthenia=asthenia.id)
    goneis=Goneis.objects.filter(asthenia=asthenia.id)
    perisotera=Perisotera.objects.filter(asthenia=asthenia.id)
    
    
    context={
        'asthenia':asthenia,
        'xaraktiristika':xaraktiristika,
        'sxolio':sxolio,
        'ekpedeftikoi':ekpedeftikoi,
        'goneis':goneis,
        'perisotera':perisotera,
    }
    return render(request, "main/info.html", context)

@login_required
def add_content(request):
    if request.method == 'POST':
        form = forms.AstheniaForm(request.POST)
        if form.is_valid():
            form.save()
            onoma = form.cleaned_data['onoma']
            asthenia = get_object_or_404(Asthenia, onoma=onoma)
            return redirect("/"+str(asthenia.id))
    return render(request, "main/add.html", {})


@login_required
def Edit_Info(request, pk):
        obj= get_object_or_404(Asthenia, id=pk)
        
        form = forms.AstheniaForm(request.POST or None, instance= obj)
        context= {'form': form}

        if form.is_valid():
            obj= form.save(commit= False)
            obj.save()
            messages.success(request, "Αποθηκεύτηκε")
            context= {
                    'form': form,
                    }
        return render(request, 'main/edit/edit_info.html', context)

@login_required
def delete(request, pk):
    obj= get_object_or_404(Asthenia, id=pk)
    if request.method=="POST":
        obj.delete()
        return redirect('/')
    context={
        'item':obj,
    }
    return render(request,'main/delete.html',context)

class Edit_Xaraktiristika(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_xaraktiristika.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaXaraktitistikaFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_xaraktiristika', kwargs={'pk':self.object.pk})
    
class Edit_Sxoleio(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_sxoleio.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaSxoleioFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_sxoleio', kwargs={'pk':self.object.pk})
    
class Edit_Ekpedeftikoi(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_ekpedeftikoi.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaEkpedeftikoiFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_ekpedeftikoi', kwargs={'pk':self.object.pk})
    
class Edit_Goneis(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_goneis.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaGoneisFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_goneis', kwargs={'pk':self.object.pk})
    
class Edit_Sindesmoi(SingleObjectMixin, FormView):
    model = Asthenia
    template_name = 'main/edit/edit_sindesmoi.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Asthenia.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return forms.AstheniaPerisoteraFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Αποθηκεύτηκε'
        )
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('main:edit_sindesmoi', kwargs={'pk':self.object.pk})

app/main/templates/main/edit/edit.html
{% extends 'base.html' %}
{% load group %}

{% block css %}
<style>
    textarea{
        height:auto;
        min-width:100%;
        max-width: 100%;
        resize: none;
        border-left: 0;
        border-right: 0;
    }
    textarea:focus{
    outline-offset: 0px #01579b !important;
    outline: none !important;
    border: 1px solid #01579b !important;
    box-shadow: 0 0 3px #01579b !important;
    -moz-box-shadow: 0 0 3px #01579b !important;
    -webkit-box-shadow: 0 0 3px #01579b !important;


    }
    [type="checkbox"]:not(:checked), 
    [type="checkbox"]:checked{
        opacity: 1;
        margin-top: 7px;
        margin-left: -15px;

    }

    hr{
        height: 3px;
        background-color: #01579b;
        border: none;
    }

    #save{
        position: fixed;
        bottom: 10px;
        right: 10px;
    }
    @media (max-width : 1024px) {
            .breadcrumb {
        font-size: 14px;
        }
        .breadcrumb:before {
            margin: 0px;
        }
    }
    
    
</style>


{% endblock %}
{% block content %}


    <form action="" method="POST" enctype="multipart/form-data">

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.management_form }}
    {{ form.non_form_errors }}
    
    {% block form %}
    {% endblock %}

    <button id="save" type="submit" class="btn btn-floating waves-effect waves-light  light-blue darken-4  right"><i class="material-icons ">save</i></button>
    </form>
{% endblock %}

{% block javascript %}
    {% if True != request.user|has_group:"admin" %}
        <script>
            window.location.replace("../");
        </script>
    {% endif %}
    {% if messages %}
        {% for message in messages %}
        <script>
            M.toast({html: '{{message}}'})
        </script>
        {% endfor %}
    {% endif %}
    {% block extrajs %}
    {% endblock %}
            <script>
            document.querySelectorAll('[for$="-DELETE"]').forEach(element=>{ 
            element.innerHTML="Διαγραφή:";
            element.style['padding-right']='20px';
            });
            document.getElementsByTagName("HR")[0].classList.add("hide");
            </script>
{% endblock %}

app/main/templates/main/edit/edit_ekpedeftikoi.html
{% extends 'main/edit/edit.html' %}

{% block form %}
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper light-blue darken-4">
        <div class="col s12">
            <a href="/{{asthenia.id}}" class="breadcrumb">{{asthenia.onoma}}</a>
            <a href="/{{asthenia.id}}/edit" class="breadcrumb">Edit</a>
            <a href="" class="breadcrumb">Εκπεδευτικοί</a>
        </div>
        </div>
    </nav>
    </div>
            {% for item in form.forms %}
            <hr>
            {% for hidden_field in item.hidden_fields %}
                {{hidden_field.errors}}
            {% endfor %}
            <table>
            {{item.as_p}}
            </table>
            {% endfor %}
{% endblock %}

{% block extrajs %}
    <script>
    document.querySelectorAll('[for$="-odigia"]').forEach(element=>{ 
    element.innerHTML="Οδηγία";
    });
    </script>
{% endblock %}

app/main/templates/main/edit/edit_goneis.html
{% extends 'main/edit/edit.html' %}

{% block form %}
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper light-blue darken-4">
        <div class="col s12">
            <a href="/{{asthenia.id}}" class="breadcrumb">{{asthenia.onoma}}</a>
            <a href="/{{asthenia.id}}/edit" class="breadcrumb">Edit</a>
            <a href="" class="breadcrumb">Γονείς</a>
        </div>
        </div>
    </nav>
    </div>
            {% for item in form.forms %}
            <hr>
            {% for hidden_field in item.hidden_fields %}
                {{hidden_field.errors}}
            {% endfor %}
            <table>
            {{item.as_p}}
            </table>
            {% endfor %}
{% endblock %}

{% block extrajs %}
    <script>
    document.querySelectorAll('[for$="-odigia"]').forEach(element=>{ 
    element.innerHTML="Οδηγία";
    });
    </script>
{% endblock %}

app/main/templates/main/edit/edit_info.html
{% extends 'base.html' %}
{% load group %}

{% block css %}
<style>
    textarea{
        min-height:300px;
        min-width:100%;
        max-width: 100%;
        resize: none;
        border-left: 0;
        border-right: 0;
    }
    textarea:focus{
    outline-offset: 0px #01579b !important;
    outline: none !important;
    border: 1px solid #01579b !important;
    box-shadow: 0 0 3px #01579b !important;
    -moz-box-shadow: 0 0 3px #01579b !important;
    -webkit-box-shadow: 0 0 3px #01579b !important;
    }
    .dropdown-content{
        min-width: 150px;
    }
</style>
{% endblock %}

{% block content %}

{% include 'nav.html' %}

<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" value="Save" class="btn waves-effect waves-light light-blue darken-4">ΑΠΟΘΗΚΕΥΣΗ</button>
    <a href="../delete/" class="btn red">ΔΙΑΓΡΑΦΗ</a>
    <a class='dropdown-trigger btn btn-floating light-blue darken-4' href='#' data-target='dropdown'><i id="edit_icon" class="material-icons ">edit</i></a>
    <a href="{% url 'main:home'%}" class="light-blue-text text-darken-4">ΑΚΥΡΩΣΗ</a>
</form>

<ul id='dropdown' class='dropdown-content' >
    <li><a href="xaraktiristika"  class="light-blue-text text-darken-4">Χαρακτηριστηκά</a></li>
    <li><a href="sxoleio"  class="light-blue-text text-darken-4">Σχολείο</a></li>
    <li><a href="ekpedeftikoi"  class="light-blue-text text-darken-4">Εκπεδευτικοί</a></li>
    <li><a href="goneis"  class="light-blue-text text-darken-4">Γονείς</a></li>
    <li><a href="sindesmoi"  class="light-blue-text text-darken-4">Σύνδεσμοι</a></li>
  </ul>

{% endblock %}

{% block javascript %}
    {% if messages %}
    {% for message in messages %}
    <script>
        M.toast({html: '{{message}}'})
    </script>
    {% endfor %}
    {% endif %}
    <script>
        document.querySelectorAll('[for$="id_onoma"]').forEach(element=>{ 
        element.innerHTML="Όνομα:";
        });
        document.querySelectorAll('[for$="id_orismos"]').forEach(element=>{ 
        element.innerHTML="Ορισμός:";
        });
        $('.dropdown-trigger').dropdown();
    </script>
{% endblock %}

app/main/templates/main/edit/edit_sindesmoi.html
{% extends 'main/edit/edit.html' %}

{% block form %}
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper light-blue darken-4">
        <div class="col s12">
            <a href="/{{asthenia.id}}" class="breadcrumb">{{asthenia.onoma}}</a>
            <a href="/{{asthenia.id}}/edit" class="breadcrumb">Edit</a>
            <a href="" class="breadcrumb">Σύνδεσμοι</a>
        </div>
        </div>
    </nav>
    </div>
            {% for item in form.forms %}
            <hr>
            {% for hidden_field in item.hidden_fields %}
                {{hidden_field.errors}}
            {% endfor %}
            <table>
            {{item.as_p}}
            </table>
            {% endfor %}
{% endblock %}

{% block extrajs %}
    <script>
    document.querySelectorAll('[for$="-link"]').forEach(element=>{ 
    element.innerHTML="Σύνδεσμος";
    });
    </script>
{% endblock %}

app/main/templates/main/edit/edit_sxoleio.html
{% extends 'main/edit/edit.html' %}

{% block form %}
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper light-blue darken-4">
        <div class="col s12">
            <a href="/{{asthenia.id}}" class="breadcrumb">{{asthenia.onoma}}</a>
            <a href="/{{asthenia.id}}/edit" class="breadcrumb">Edit</a>
            <a href="" class="breadcrumb">Σχολείο</a>
        </div>
        </div>
    </nav>
    </div>
            {% for item in form.forms %}
            <hr>
            {% for hidden_field in item.hidden_fields %}
                {{hidden_field.errors}}
            {% endfor %}
            <table>
            {{item.as_p}}
            </table>
            {% endfor %}
{% endblock %}

{% block extrajs %}
    <script>
    document.querySelectorAll('[for$="-odigia"]').forEach(element=>{ 
    element.innerHTML="Οδηγία";
    });
    </script>
{% endblock %}

app/main/templates/main/edit/edit_xaraktiristika.html
{% extends 'main/edit/edit.html' %}

{% block form %}
<div class="navbar-fixed">
<nav>
    <div class="nav-wrapper light-blue darken-4">
    <div class="col s12">
        <a href="/{{asthenia.id}}" class="breadcrumb">{{asthenia.onoma}}</a>
        <a href="/{{asthenia.id}}/edit" class="breadcrumb">Edit</a>
        <a href="" class="breadcrumb">Χαρακτηριστηκά</a>
    </div>
    </div>
</nav>
</div>
        {% for item in form.forms %}
        <hr>
        {% for hidden_field in item.hidden_fields %}
            {{hidden_field.errors}}
        {% endfor %}
        <table>
        {{item.as_p}}
        </table>
        {% endfor %}
        
{% endblock %}

{% block extrajs %}
    <script>
    document.querySelectorAll('[for$="-xaraktiristiko"]').forEach(element=>{ 
    element.innerHTML="Χαρακτηριστικό";
    });
    </script>
{% endblock %}